# Generated by Django 4.1 on 2022-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseForm',
            fields=[
                ('CaseId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('TicketNumber', models.CharField(max_length=500)),
                ('DriverLicense', models.CharField(max_length=500)),
            ],
        ),
    ]
